const timeA = new Date().getTime()
console.log('NODE_ENV', process.env.NODE_ENV)
console.log('process env', process.argv)
var fs = require('fs')
var babelConfig = JSON.parse(fs.readFileSync('./.babelrc'))
require('babel-register')(babelConfig)
require('./puppetter/TimeoutError.js')
const timeB = new Date().getTime()
console.log('运行时间', timeB - timeA)
